#!/bin/sh
set -ex

git up
git checkout production
git add --all
git commit -m "Update static build - `date -u`"
# Setting up the remote:
# `git remote add 5apps git@5apps.com:silverbucket_sharesome.git`
git push subtree 5apps production:master
git push upstream production
git checkout master
