#!/bin/sh
set -ex

git up
git checkout production
git merge master
npm run build:dist
git add -f dist/
git commit -m "Update static build - `date -u`" dist/
# Setting up the remote:
# `git remote add 5apps git@5apps.com:silverbucket_sharesome.git`
git push 5apps `git subtree split --prefix dist/ production`:master --force
git push upstream production
git checkout master
